version: '3.8'
services:
  # React.js app service
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


# version: '3.8'
# services:
#   # TypeScript app service
#   typescript_app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app


# version: "3.8"
# services:
#  web:
#  image: shahzaib2468/quiz-react-app:latest
#  ports:
#  - "3000:3000
